version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "web:start"]
    ports:
      - "127.0.0.1:3000:3000"

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   entrypoint: ["npm run start:api"]
  #   ports:
  #     - "127.0.0.1:3001:3001"