services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: ["npm", "run", "web:dev"]
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:3000:3000"
    env_file: ".env"

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: ["npm", "run", "api:dev"]
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:3001:3001"
    env_file: ".env"
