services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "web:start"]
    ports:
      - "127.0.0.1:3000:3000"
    env_file: ".env"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "api:start"]
    ports:
      - "127.0.0.1:3001:3001"
    env_file: ".env"
